# Generated by Django 4.1.7 on 2023-04-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dissertations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='uploads/%Y/%m'),
        ),
    ]
