# Generated by Django 4.1.7 on 2023-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dissertations', '0003_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='users/%Y/%m'),
        ),
    ]
